### ISSUE TITLE
Will the qwen2.5 model be supported in the future？

### ISSUE THREAD

**Issue by qingkongby** [OpenGVLab/OmniQuant#101]

**Comment by ChenMnZ** [comment]
We have no plan to support other models in this repo. You can see our latest quantization algorithm [PrefixQuant](https://github.com/ChenMnZ/PrefixQuant), which supports Qwen models.

Additionally, the quantization toolkit [llmc](https://github.com/ModelTC/llmc) supports OmniQuant algorithm and Qwen modelss, you can also have a check.
