### ISSUE TITLE
mlc notebook provided doesnt run on colab

### ISSUE THREAD

**Issue by githubpradeep** [OpenGVLab/OmniQuant#15]
error vocab_size not found

**Comment by ChenMnZ** [comment]
Which code produced this error?

**Comment by githubpradeep** [comment]
please run it on google colab you will see the error

**Comment by ChenMnZ** [comment]
Thanks for your feedback. I find that this bug is caused by mlc-llm.
So runing_quantized_models_with_mlc_llm.ipynb can not be use until official mlc-llm fixing their bug.
I will fix this after mlc-llm fix the bug of there repo.
