### ISSUE TITLE
Runing quantized models with MLC-LLM error 

### ISSUE THREAD

**Issue by silvacarl2** [OpenGVLab/OmniQuant#18]
this line:

cm = ChatModule(model="dist/Llama-2-7b-chat-omniquant-w3a16g128asym/params", lib_path="dist/Llama-2-7b-chat-omniquant-w3a16g128asym/Llama-2-7b-chat-omniquant-w3a16g128asym-cuda.so")

produces this error:

JSONDecodeError: Expecting property name enclosed in double quotes: line 18 column 1 (char 497)

**Comment by silvacarl2** [comment]
ok, cool will check back on this.

**Comment by siddu9501** [comment]
There are rogue characters on this line.
https://huggingface.co/ChenMnZ/Llama-2-7b-chat-omniquant-w3a16g128asym/blob/main/params/mlc-chat-config.json#L18
delete the blank spaces preceding the line and redo the spaces in any text editor.
