### ISSUE TITLE
Results Errors

### ISSUE THREAD

**Issue by yileijin** [OpenGVLab/OmniQuant#25]
Could you please tell me how you got your ppl results on the wikitext2 in LLaMa models, I reused your ckpt but found there are some disparities.

**Comment by ChenMnZ** [comment]
You can reproduce the results by:
```
CUDA_VISIBLE_DEVICES=0 python main.py \
--model /PATH/TO/LLaMA/llama-7b  \
--epochs 0 --output_dir ./log/test \
--eval_ppl --wbits 3 --abits 16 --group_size 128 --lwc \
--resume /PATH/TO/Pretrained/Parameters 
```

Maybe you can provide more details about the command you used and the results  you get.

**Comment by yileijin** [comment]
parser.add_argument("--model", default="huggyllama/llama-7b", type=str, help="model name of model path")
 parser.add_argument("--cache_dir", default="./cache", type=str, help="cache dir of dataset, leading to faster debug")
  parser.add_argument("--output_dir", default="./log/llama7b_w4a16g128", type=str, help="direction of logging file")
  parser.add_argument("--save_dir", default='./ckpt/llama7b_test', type=str, help="direction for saving fake quantization model")
  parser.add_argument("--real_quant", default=False, action="store_true",)
  parser.add_argument("--calib_dataset",type=str,default="wikitext2",
      choices=["wikitext2", "ptb", "c4", "mix","pile"],
      help="Where to extract calibration data from.",
  )

  parser.add_argument("--omni_resume", type=str, default='./llama-7b-w4a16g128.pth)
  
  parser.add_argument("--nsamples", type=int, default=128, help="Number of calibration data samples.")
  parser.add_argument("--batch_size", type=int, default=16, help="batch size.")
  parser.add_argument("--epochs", type=int, default=0)
 
  parser.add_argument("--seed", type=int, default=2, help="Seed for sampling the calibration data.")
  parser.add_argument("--tasks", default='')
  parser.add_argument("--eval_ppl", default=True, action="store_true")
  parser.add_argument("--num_fewshot", type=int, default=0)

  parser.add_argument("--wbits", type=int, default=4)
  parser.add_argument("--abits", type=int, default=16)
  parser.add_argument("--group_size", type=int, default=128)

  parser.add_argument("--alpha", type=float, default=0.5)
  parser.add_argument("--let_lr", type=float, default=5e-3)
  parser.add_argument("--lwc_lr", type=float, default=1e-2)
  parser.add_argument("--wd", type=float, default=0)

  parser.add_argument("--let",default=True, action="store_true",help="activate learnable equivalent transformation")
  parser.add_argument("--lwc",default=True, action="store_true",help="activate learnable weight clipping")
  parser.add_argument("--aug_loss", default=False, action="store_true", help="calculate additional loss with same input")
  parser.add_argument("--symmetric", default=False, action="store_true", help="symmetric quantization")

You see, the final results of your released ckpt in huggingface is:
[2023-10-11 00:50:31 root] (main.py 157): INFO {'results': {'wikitext': {'word_perplexity': 22.08906210357998, 'byte_perplexity': 1.8170466512610957, 'bits_per_byte': 0.8615954601218602}}, 'versions': {'wikitext': 1}, 'config': {'model': <models.LMClass.LMClass object at 0x7fb87d2a5250>, 'model_args': None, 'num_fewshot': 0, 'limit': None, 'bootstrap_iters': 100000, 'description_dict': None}}

I have tested several times, and I'm doing work inspired by yours. So I need to figure out how it is exactly.

**Comment by yileijin** [comment]
sorry, not this result, it's the whole wikitext2, the w4a16 without group result is:
[2023-10-09 22:45:41 root] (main.py 146): INFO wikitext2 : 6.04078483581543

**Comment by yileijin** [comment]
And the w3a16g128 results:
2023-10-10 02:02:05 root] (main.py 146): INFO wikitext2 : 6.360328197479248
w3a16 results: (I even tested twice)
[2023-10-10 19:14:14 root] (main.py 146): INFO wikitext2 : 9.61421012878418
[2023-10-10 19:34:51 root] (main.py 146): INFO wikitext2 : 9.61421012878418

**Comment by ChenMnZ** [comment]
I have tested the checkpoints on this codebase with the following command just now:
```
CUDA_VISIBLE_DEVICES=2 python main.py \
--model /cpfs01/user/chenmengzhao/llama_quantization/llama-hf/llama-7b  \
--output_dir ./log/test \
--epochs 0 --nsamples 128 \
--wbits 3 --abits 16 --group_size 128 --lwc --aug_loss --eval_ppl \
--lwc_lr 0 \
--resume /cpfs01/user/chenmengzhao/prompt_quantization/OmniQuant/huggingface/OmniQuant/llama-7b-w3a16g128.pth
```
and the results is：
···
[2023-10-19 05:29:03 root](main.py 146): INFO wikitext2 : 6.15703010559082
···
So, I don't sure what problem with you. Whether you have changed some code that leads this problem.

**Comment by yileijin** [comment]
Thanks, I will reload the project to try

**Comment by ChenMnZ** [comment]
Through the above command, maybe I find your problem.

You should not use  `--let` in the command. For the quantization of LLaMa, we only use `--lwc`.

You will obtain the correct results when discard `--let`.

Thanks for your follow, you can add my WeChat (id: chenmnz1) for further discussion.

**Comment by brisker** [comment]
@ChenMnZ 
In the paper you mentioned LWC is better than LSQ and PACT, but in my opinion, there seems no difference among these methods. If weights are quantized **symmetrically** quantized, learnable quantization step size is equivalent to learnable clipping threshold, right? Then LWC is just like LSQ or PACT

**Comment by ChenMnZ** [comment]
@brisker 
In our paper, we used both LWC and LET. LET will change the magnitude of weight continuity, leading that directly learn step size or clipping threshold is unstable for training.
So, we designed LWC, which learn clipping threshold by taking the maximum and minimum value after LET as a proxy, which is benefit for the training stability.
