### ISSUE TITLE
Is evaluation on MMLU dataset supported?

### ISSUE THREAD

**Issue by brisker** [OpenGVLab/OmniQuant#30]
Is evaluation on MMLU dataset supported? I can find corresponding codes here:
`https://github.com/OpenGVLab/OmniQuant/blob/main/categories.py`
But can not find any API which can be called.

**Comment by ChenMnZ** [comment]
If you want to get the results on MMLU, you should add `--tasks hendrycksTest*` in your command.

**Comment by Forival** [comment]
How to load the quantized model to evaluate?
I want to test other performances besides zero-shot, including memory usage and token processing efficiency etc...

**Comment by brisker** [comment]
@ChenMnZ 
another puzzle:
why is the Llama fp16 accuracy in your paper different from the results reported in Llama-2 paper?

`Results in your paper:`


![image](https://github.com/OpenGVLab/OmniQuant/assets/13804492/27706444-2ab1-448f-84ac-097cf19e76b8)


Results in [Llama-2 paper](https://arxiv.org/pdf/2307.09288.pdf):
![image](https://github.com/OpenGVLab/OmniQuant/assets/13804492/3a240f14-dc0a-4eae-924f-71cab8e8828f)

**Comment by ChenMnZ** [comment]
@brisker 
Different process methods will lead to different results, you may get more details through LLAMA2's paper or repo. 

In my paper, I evaluate all zero-shot tasks through https://github.com/EleutherAI/lm-evaluation-harness, which is popular in the community.

You can also reproduce the reported results in my paper easily through lm-evaluation-harness.

**Comment by Forival** [comment]
> @brisker Different process methods will lead to different results, you may get more details through LLAMA2's paper or repo.
> 
> In my paper, I evaluate all zero-shot tasks through https://github.com/EleutherAI/lm-evaluation-harness, which is popular in the community.
> 
> You can also reproduce the reported results in my paper easily through lm-evaluation-harness.

How to load the quantized model to evaluate?
I want to test other performances besides zero-shot, including memory usage and token processing efficiency etc...

**Comment by tro0o** [comment]
I evaluated five zero-shot tasks through lm-evaluation-harness, but the results I obtained show significant differences from the metrics presented in your paper.
![image](https://github.com/OpenGVLab/OmniQuant/assets/73322319/e82c9c0b-a516-4058-a533-d25eb8de1f5a)

**Comment by ChenMnZ** [comment]
@Forival 
If you want to reproduce the zero-shot accuracy or perplexity of quantization models, you can refer `reproduce evaluation results of our paper` in https://github.com/OpenGVLab/OmniQuant#usage for mor details.
If you want to obtain practical memory reduction and speedup, you should leverage mlc-llm, refer https://github.com/OpenGVLab/OmniQuant/blob/main/runing_quantized_models_with_mlc_llm.ipynb for more details.

**Comment by ChenMnZ** [comment]
@tro0o 
There are two reasons.
- First, lm-evaluation-harness have updated their code, which would affect the evaluated accuracy. You can use our repo to reproduce the results.
- Second, for dataset has both `acc` and `acc_norm` (i.e. arc-e and arc-c), we reported the `acc-norm`.

**Comment by brisker** [comment]
@ChenMnZ 
adding` --tasks hendrycksTest` in command leads to NaN results on MMLU dataset:

```
[2023-11-17 14:24:34 root](main.py 157): INFO {'results': {}, 'versions': {}, 'config': {'model': <models.LMClass.LMClass object at 0x7fa11e7be190>, 'model_args': None, 'num_fewshot': 0, 'limit': None, 'bootstrap_iters': 100000, 'description_dict': None}}
{'config': {'bootstrap_iters': 100000,
            'description_dict': None,
            'limit': None,
            'model': <models.LMClass.LMClass object at 0x7fa11e7be190>,
            'model_args': None,
            'num_fewshot': 0},
 'results': {},
 'versions': {}}
/usr/local/miniconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/miniconda3/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[2023-11-17 14:24:34 root](main.py 184): INFO Average accuracy nan - STEM
[2023-11-17 14:24:34 root](main.py 184): INFO Average accuracy nan - humanities
[2023-11-17 14:24:34 root](main.py 184): INFO Average accuracy nan - social sciences
[2023-11-17 14:24:34 root](main.py 184): INFO Average accuracy nan - other (business, health, misc.)
[2023-11-17 14:24:34 root](main.py 186): INFO Average accuracy: nan
```

**Comment by ChenMnZ** [comment]
@brisker 
It is `--tasks hendrycksTest*`, but not `--tasks hendrycksTest`.

**Comment by brisker** [comment]
@ChenMnZ 
using `--tasks hendrycksTest*`,  something went wrong:

```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:41<00:00, 20.67s/it]
vocab size:  32000
Selected Tasks: ['hendrycksTest-electrical_engineering', 'hendrycksTest-elementary_mathematics', 'hendrycksTest-public_relations', 'hendrycksTest-high_school_psychology', 'hendrycksTest-high_school_macroeconomics', 'hendrycksTest-high_school_chemistry', 'hendrycksTest-high_school_mathematics', 'hendrycksTest-virology', 'hendrycksTest-college_physics', 'hendrycksTest-human_aging', 'hendrycksTest-logical_fallacies', 'hendrycksTest-professional_medicine', 'hendrycksTest-high_school_world_history', 'hendrycksTest-computer_security', 'hendrycksTest-global_facts', 'hendrycksTest-human_sexuality', 'hendrycksTest-high_school_us_history', 'hendrycksTest-professional_law', 'hendrycksTest-professional_psychology', 'hendrycksTest-business_ethics', 'hendrycksTest-jurisprudence', 'hendrycksTest-moral_scenarios', 'hendrycksTest-world_religions', 'hendrycksTest-college_chemistry', 'hendrycksTest-high_school_geography', 'hendrycksTest-high_school_microeconomics', 'hendrycksTest-prehistory', 'hendrycksTest-machine_learning', 'hendrycksTest-security_studies', 'hendrycksTest-marketing', 'hendrycksTest-abstract_algebra', 'hendrycksTest-high_school_government_and_politics', 'hendrycksTest-high_school_european_history', 'hendrycksTest-college_medicine', 'hendrycksTest-conceptual_physics', 'hendrycksTest-us_foreign_policy', 'hendrycksTest-management', 'hendrycksTest-medical_genetics', 'hendrycksTest-professional_accounting', 'hendrycksTest-astronomy'Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:41<00:00, 20.67s/it]
vocab size:  32000
Selected Tasks: ['hendrycksTest-electrical_engineering', 'hendrycksTest-elementary_mathematics', 'hendrycksTest-public_relations', 'hendrycksTest-high_school_psychology', 'hendrycksTest-high_school_macroeconomics', 'hendrycksTest-high_school_chemistry', 'hendrycksTest-high_school_mathematics', 'hendrycksTest-virology', 'hendrycksTest-college_physics', 'hendrycksTest-human_aging', 'hendrycksTest-logical_fallacies', 'hendrycksTest-professional_medicine', 'hendrycksTest-high_school_world_history', 'hendrycksTest-computer_security', 'hendrycksTest-global_facts', 'hendrycksTest-human_sexuality', 'hendrycksTest-high_school_us_history', 'hendrycksTest-professional_law', 'hendrycksTest-professional_psychology', 'hendrycksTest-business_ethics', 'hendrycksTest-jurisprudence', 'hendrycksTest-moral_scenarios', 'hendrycksTest-world_religions', 'hendrycksTest-college_chemistry', 'hendrycksTest-high_school_geography', 'hendrycksTest-high_school_microeconomics', 'hendrycksTest-prehistory', 'hendrycksTest-machine_learning', 'hendrycksTest-security_studies', 'hendrycksTest-marketing', 'hendrycksTest-abstract_algebra', 'hendrycksTest-high_school_government_and_politics', 'hendrycksTest-high_school_european_history', 'hendrycksTest-college_medicine', 'hendrycksTest-conceptual_physics', 'hendrycksTest-us_foreign_policy', 'hendrycksTest-management', 'hendrycksTest-medical_genetics', 'hendrycksTest-professional_accounting', 'hendrycksTest-astronomy', 'hendrycksTest-clinical_knowledge', 'hendrycksTest-formal_logic', 'hendrycksTest-econometrics', 'hendrycksTest-college_computer_science', 'hendrycksTest-international_law', 'hendrycksTest-nutrition', 'hendrycksTest-high_school_physics', 'hendrycksTest-philosophy', 'hendrycksTest-moral_disputes', 'hendrycksTest-miscellaneous', 'hendrycksTest-high_school_computer_science', 'hendrycksTest-anatomy', 'hendrycksTest-high_school_statistics', 'hendrycksTest-high_school_biology', 'hendrycksTest-college_mathematics', 'hendrycksTest-college_biology', 'hendrycksTest-sociology']
Traceback (most recent call last):
  File "main.py", line 370, in <module>
    main()
  File "main.py", line 365, in main
    evaluate(lm, args,logger)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "main.py", line 150, in evaluate
    t_results = evaluator.simple_evaluate(
  File "/data1/projects/OmniQuant-main/lm_eval/utils.py", line 160, in _wrapper
    return fn(*args, **kwargs)
  File "/data1/projects/OmniQuant-main/lm_eval/evaluator.py", line 69, in simple_evaluate
    results = evaluate(
  File "/data1/projects/OmniQuant-main/lm_eval/utils.py", line 160, in _wrapper
    return fn(*args, **kwargs)
  File "/data1/projects/OmniQuant-main/lm_eval/evaluator.py", line 178, in evaluate
    task_docs = list(task_doc_func())
  File "/data1/projects/OmniQuant-main/lm_eval/tasks/hendrycks_test.py", line 127, in test_docs
    return map(self._process_doc, self.dataset["test"])
AttributeError: 'HendrycksTest' object has no attribute 'dataset'
```

**Comment by brisker** [comment]
@ChenMnZ 
already replacing all the files in `lm_eval` folder, except for `evaluator.py`, but still different results for fp16 on winogrande datasets:
omniquant-fp16: ` 67.24`
lm-eval-original-code(https://github.com/EleutherAI/lm-evaluation-harness):` 69.22`
but in my understanding, the difference in evaluator.py can not influence the accuracy.
Is there any other reasons causing the accuracy difference?

**Comment by ChenMnZ** [comment]
@brisker 
This repo load model with `float16` type. 
https://github.com/OpenGVLab/OmniQuant/blob/834847adcee9575b89cd14ed2a3623c770743b4a/models/LMClass.py#L26

You can try to replace `float16` with `bfloat16`.

**Comment by brisker** [comment]
@ChenMnZ 
but in the  

llama2-7b-lm-eval-original-code-fp16(https://github.com/EleutherAI/lm-evaluation-harness):  69.22

I also use float16

**Comment by ChenMnZ** [comment]
@brisker 
You can try to replace the `evaluator.py` and modified the `simple_evaluate` function to fit original omniquant code.

I think such a difference accuracy is caused by some update in `evaluator.py`.

**Comment by brisker** [comment]
@ChenMnZ 
Is there any chance that , the difference beween `main.py `is causing the accuracy difference?
