### ISSUE TITLE
[Model Request] Mixtral-8x7B-v0.1 

### ISSUE THREAD

**Issue by joseph777111** [OpenGVLab/OmniQuant#40]
The Mixtral-8x7B Large Language Model (LLM) is a pretrained generative Sparse Mixture of Experts. The Mistral-8x7B outperforms Llama 2 70B on most benchmarks we tested.

For full details of this model please read our [release blog post](https://mistral.ai/news/mixtral-of-experts/).

 https://huggingface.co/mistralai/Mixtral-8x7B-v0.1

**Comment by ChenMnZ** [comment]
Thanks for your proposal. I am working for this, please wait a moment.

**Comment by ChenMnZ** [comment]
We have supported [Mixtral-8x7B-v0.1](https://huggingface.co/mistralai/Mixtral-8x7B-v0.1), please refer the latest code for more details. Some results based on [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness) is as follows:
<img width="966" alt="mixtral_7bx8_v0 1" src="https://github.com/OpenGVLab/OmniQuant/assets/57585796/655616e1-15ce-468d-9012-ccedce67b232">

**Comment by joseph777111** [comment]
Thank you! You guys are freaking awesome!!!! 🤩
