### ISSUE TITLE
how to run Android app of release v0.0.1

### ISSUE THREAD

**Issue by 946166920** [OpenGVLab/OmniQuant#5]
I install the app of  release v0.0.1.
It show Add model failed: no protocol: /resolve/main/mlc-chat-config.json

**Comment by ChenMnZ** [comment]
The app includes three pre-configured models as shown here:
![4d53b06ba6eb8d60ea84dad860ec45e](https://github.com/OpenGVLab/OmniQuant/assets/57585796/b439245a-6167-41ee-b4f6-449752b37e4c)
Upon launch, these models are automatically integrated. For manual addition, please input any of the following links into the `Model URL` bar:
```
https://huggingface.co/ChenMnZ/Llama-2-13b-chat-omniquant-w3a16g128asym_2/
https://huggingface.co/ChenMnZ/Llama-2-7b-chat-omniquant-w3a16g128asym_2/
https://huggingface.co/ChenMnZ/Llama-2-13b-chat-omniquant-w2a16g128asym_2/
```
