### ISSUE TITLE
W4A4 in llama2-7b

### ISSUE THREAD

**Issue by chenzx921020** [OpenGVLab/OmniQuant#70]
When I do W4A4 weight-activation quantization with Omniquant on llama2-7b, I found ppl in wikitext2 is unstable, in 3090 is 17.24, in A6000 is 19.95, all settings is following paper, but in paper it's 14.26. 
Why does the above phenomenon occur？

**Comment by ChenMnZ** [comment]
What command did you use?

**Comment by chenzx921020** [comment]
> What command did you use?

['main.py', '--model', '/data01/llama2-7b-hf/', '--epochs', '20', '--output_dir', './log/llama--7b-w4a4', '--eval_ppl', '--wbits', '4', '--abits', '4', '--lwc', '--let', '--act-scales', './act_scales/llama2-7b.pt', '--act-shifts', './act_shifts/llama2-7b.pt', '--net', 'Llama-2-7b']

**Comment by ChenMnZ** [comment]
Please following [this script](https://github.com/OpenGVLab/OmniQuant/blob/main/scripts/Llama-2/Llama-2-7b/w4a4.sh):
```
CUDA_VISIBLE_DEVICES=0 python main.py \
--model /PATH/TO/LLaMa/Llama-2-7b --eval_ppl \
--epochs 20 --output_dir ./log/Llama-2-7b-w4a4 \
--wbits 4 --abits 4 --lwc --let  \
--let_lr 1e-3 --alpha 0.75
```

**Comment by chenzx921020** [comment]
ok， thankyou

**Comment by threeEggPie** [comment]
I also encountered this problem. How about it? Did you manage to successfully reproduce the 14.26 in the paper? I used Omniquant on llama2-7b for W4A4 weight activation quantization. The INFO I got for wikitext2 was: 16.66050910949707.
The script I used was: 
`
CUDA_VISIBLE_DEVICES=1 python main.py \
--model meta-llama/Llama-2-7b-hf --eval_ppl \
--epochs 20 --output_dir ./log/Llama-2-7b-w4a4 \
--wbits 4 --abits 4 --lwc --let  \
--let_lr 1e-3 --alpha 0.75
`
The file "Llama-2-7b.pt" was downloaded from https://huggingface.co/ChenMnZ/act_shifts and is referred to as "act_scales". I don't know whether it's my operation that has gone wrong or something else. If you can help me, I would be extremely grateful.
