### ISSUE TITLE
AttributeError: 'FalconAttention' object has no attribute 'maybe_rotary'

### ISSUE THREAD

**Issue by luchangli03** [OpenGVLab/OmniQuant#71]
OmniQuant-main/models/int_falcon_layer.py", line 52, in __init__
    self.maybe_rotary = copy.deepcopy(org_module.maybe_rotary)
  File "local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FalconAttention' object has no attribute 'maybe_rotary'

transformers version: 4.39.3

**Comment by chaibosong** [comment]
I encountered the same issue. It seems that the transformers package does not have maybe_rotary. How did you solve this problem later?I tried different versions of the transformers package.

transformers version: 4.32.0
