### ISSUE TITLE
Why is the compressed file one file instead of the pre trained weights, where there are many files for training the mode

### ISSUE THREAD

**Issue by hsb1995** [OpenGVLab/OmniQuant#73]
![image](https://github.com/OpenGVLab/OmniQuant/assets/149936473/b86fe737-3287-41ed-8b10-963e71e3677c)
Why is the compressed file one file instead of the pre trained weights, where there are many files for training the model? Can the compressed file be used for downstream tasks? It feels strange

**Comment by ChenMnZ** [comment]
We only save the parameters for `let` and `lwc` for training. 

To save the quantized model, set the `--save_dir` argument.
