### ISSUE TITLE
Is activation get quantized on-the-fly?

### ISSUE THREAD

**Issue by XA23i** [OpenGVLab/OmniQuant#74]
In inference, the scales and zero points in activation are adjusted dynamically according to inputs. They do not get fixed in inference. Does it?

**Comment by Alvant** [comment]
@XA23i Yes, I believe you are right. Activations are really quantized on the fly...

So, personally, I quantized only weights (`w4a16g128` setting). Also, even if scales and zero points were fixed, [it seems that GPTQ does not support activation quantization at all](https://github.com/OpenGVLab/OmniQuant)...

**Comment by XA23i** [comment]
thanks. By the way,  if Activations are quantized on the fly, how will the latency be compared to fixed activation quantization?

**Comment by ChenMnZ** [comment]
@XA23i 
We only explore the deployment of weight-only quantization in this study due to that W4A4 and W6A6 quantization methods lack out-of-the-box hardware support.

**Comment by XA23i** [comment]
I seem, thank you.
