### ISSUE TITLE
why quantize opt-1.3b or llama 7b with W8A8 config loss is nan?

### ISSUE THREAD

**Issue by MeJerry215** [OpenGVLab/OmniQuant#8]
![image](https://github.com/OpenGVLab/OmniQuant/assets/53092165/37b058f8-87b1-43ab-89c4-02763ba03eff)

the quant command is 
`
python main.py --model llama-7B --epochs 20 --calib_dataset c4 --nsamples 128 --batch_size 1 --seed 0 --eval_ppl --wbits 4 --abits 8 --lwc --let --output_dir quant_models/llama-7b-w4a8 --save_dir fake_models/llama-7b-w4a8
`

**Comment by MeJerry215** [comment]
@ChenMnZ

**Comment by ChenMnZ** [comment]
Training with 8bit quantization would cause NAN loss in mixer-precision training.

**Comment by ChenMnZ** [comment]
Training with 8-bit quantization leads to NAN loss in mixed-precision training. 
Please refer to the updated code; we've implemented full-precision training for quantization bits greater than 8, enabling successful W4A8 training.

**Comment by MeJerry215** [comment]
> Training with 8-bit quantization leads to NAN loss in mixed-precision training. Please refer to the updated code; we've implemented full-precision training for quantization bits greater than 8, enabling successful W4A8 training.

thx a lot.

**Comment by brisker** [comment]
> Training with 8-bit quantization leads to NAN loss in mixed-precision training.

`“Training with 8-bit quantization leads to NAN loss in mixed-precision training.”`

why is this happening? 
@ChenMnZ

**Comment by ChenMnZ** [comment]
@brisker 
During the backward of mixed-precision training, gradient is calculated through `float16` format, which has a narrower representation scope.

For the 8-bit quantization, the step size of quantization is `2^8-1`. Such large step size during backward would lead overflow for `float16`.

**Comment by brisker** [comment]
@ChenMnZ 
here:   https://github.com/OpenGVLab/OmniQuant/blob/main/quantize/omniquant.py#L192

![image](https://github.com/OpenGVLab/OmniQuant/assets/13804492/c5e0bbfb-2463-4583-a347-23827b8798e2)



why are **shifts** not used in Llama model equivalent transformation?

**Comment by xingchensong** [comment]
> @ChenMnZ here: https://github.com/OpenGVLab/OmniQuant/blob/main/quantize/omniquant.py#L192
> 
> ![image](https://private-user-images.githubusercontent.com/13804492/290716110-c5e0bbfb-2463-4583-a347-23827b8798e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODIzMDcsIm5iZiI6MTcwNDE4MjAwNywicGF0aCI6Ii8xMzgwNDQ5Mi8yOTA3MTYxMTAtYzVlMGJiZmItMjQ2My00NTgzLWEzNDctMjM4MjdiODc5OGUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA3NTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTM5MGI2ODM3YWU2ZmQzN2Y2YzdlMzFmYzM5YjUxYWVlY2U2OTc2MmZmZmI4NmM0Nzc1OWQ2NjI3YTdiZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.scvS9d4BNJM5nX9rXXXkPpuzVqzfyrLx40kwmjqemdc)
> 
> why are **shifts** not used in **Llama** model equivalent transformation?

Also intrigued by the rationale behind this question.

**Comment by ChenMnZ** [comment]
The original LLaMa models do not contain `bias` parameters, and we find that shift operation can not bring benefit to weight-only quantization. Therefore, we only activate shifts equivalent transformation in the weight-activation quantization for LLaMa models.

As for the initialization, the initialization of shifts is crucial for OPT but negligible for LLaMa, so we simple init it as 1 for LLaMa.

**Comment by Xingrun-Xing** [comment]
我们试了一下4A4W的LLAMA2，为什么即使在8bit以下，如果打开半精度训练，损失依然是nan？另外，当我们使用全精度训练时，wikitext2的ppl是11.，而不是论文中的5.，我们想确认一下现在代码的版本是否可以正确运行LLAMA2，感谢！

**Comment by ChenMnZ** [comment]
@Xingrun-Xing 
我刚跑了一遍LLaMa-2-7b w4a16，现在的代码版本可以正确运行LLAMA2，你可以提供你的训练指令以进行进一步查看。
训练代码：
```
CUDA_VISIBLE_DEVICES=1 python main.py \
--model path/to/llama-7b  \
--output_dir ./log/test \
--epochs 5 --nsamples 128 \
--wbits 4 --abits 16 --lwc --eval_ppl
```
结果：
![image](https://github.com/OpenGVLab/OmniQuant/assets/57585796/7ff1877a-0c28-416f-a714-13d8a03c6fe1)

以及需要注意的是，OmniQuant会读取保存好的cache数据集，你需要保证这些cache数据集没问题，若是可能存在问题你可以把cache文件夹下的文件删除重新跑一篇OmniQuant代码。

**Comment by Xingrun-Xing** [comment]
> @Xingrun-Xing 我刚跑了一遍LLaMa-2-7b w4a16，现在的代码版本可以正确运行LLAMA2，你可以提供你的训练指令以进行进一步查看。 训练代码：
> 
> ```
> CUDA_VISIBLE_DEVICES=1 python main.py \
> --model path/to/llama-7b  \
> --output_dir ./log/test \
> --epochs 5 --nsamples 128 \
> --wbits 4 --abits 16 --lwc --eval_ppl
> ```
> 
> 结果： ![image](https://private-user-images.githubusercontent.com/57585796/309992031-7ff1877a-0c28-416f-a714-13d8a03c6fe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjQ5MjgsIm5iZiI6MTcwOTYyNDYyOCwicGF0aCI6Ii81NzU4NTc5Ni8zMDk5OTIwMzEtN2ZmMTg3N2EtMGMyOC00MTZmLWE3MTQtMTNkOGEwM2M2ZmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3NDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDNkYzk5ZjRhNmU3MWJjNTVlNTRlMzhkY2YxNTgwZDdhYjM1ZjMzZmY0NTBkYThhOTgwZGM0YWRmOWE1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XDdHYI1cVZlj_mKPcsDNTlOlysPpvaLkyGbN9Mxcnag)
> 
> 以及需要注意的是，OmniQuant会读取保存好的cache数据集，你需要保证这些cache数据集没问题，若是可能存在问题你可以把cache文件夹下的文件删除重新跑一篇OmniQuant代码。

感谢回复 我刚才重新拉现在的代码又跑了一遍，用的和你一样的命令，结果已经正常了。另外有一个小问题，我们的跑的结果略有差异，可能的原因是什么呢，请问你的transformers版本是多少
![image](https://github.com/OpenGVLab/OmniQuant/assets/48146545/afbe52a9-f570-4430-8b9d-b36d7f6f4a8b)

**Comment by Xingrun-Xing** [comment]
你好，发现另有一个问题，我们试了一下/script下的各个脚本，发现W6A6不能正常训练 LLAMA2，其他脚本都正常
![image](https://github.com/OpenGVLab/OmniQuant/assets/48146545/f25c10f0-e8b2-414e-a341-3eda36e429bf)

**Comment by ChenMnZ** [comment]
@Xingrun-Xing 
1. transformer version 4.36.0。结果差异可以尝试下载[训练好的量化参数](https://huggingface.co/ChenMnZ/OmniQuant/tree/main)进行测试，排查是否环境存在问题。若是环境没问题，训练好的量化参数应该能得到和论文中差不多的结果。
2. W6A6遇到NAN尝试加入--deactive_amp应该可解决

**Comment by haoming-codes** [comment]
> 2. W6A6遇到NAN尝试加入--deactive_amp应该可解决

May I ask if you know why torch.amp does not work with W6A6? Thank you for the great work.

**Comment by Wotoosh** [comment]
Dear sir, when using w6a6.sh, I have encountered the same problem that the norm is nan, after using "--deactive_amp"，in QuantLinear'forward(), the line of  "out = self.fwd_func(input, weight, bias, **self.fwd_kwargs)" would cause "mat1 and mat2 must have the same dtype, but got Float and Half". However, after I change both weight and input into float32, it would cause "self and mat2 must have the same dtype, but got Half and Float", when I change them both into float16, it would cause "self and mat2 must have the same dtype, but got Float and Half". Using autocast before the line woudn't cause this problem ,but the norm would still be nan. Should I change other code after using the "--deactive_amp"?Thank you @ChenMnZ

**Comment by ChenMnZ** [comment]
@Wotoosh Do you use the packages with recommend version?

Additionally, recommending you to use our new algorithm, [PrefixQuant](https://github.com/ChenMnZ/PrefixQuant), which is stronger and without NAN problem.

**Comment by Wotoosh** [comment]
some versions are higher than the least-needed, but thanks, your work is really strong
