### ISSUE TITLE
The llama-1-65b model seems unstable in this code

### ISSUE THREAD

**Issue by Xingrun-Xing** [OpenGVLab/OmniQuant#83]
Dear authors, we have tried llama-1-65b omniquant in 4A4W following the given script. It is not stable nor successful in training as follows. The training scheme is the same. Are there any solutions to fix it?  
![image](https://github.com/OpenGVLab/OmniQuant/assets/48146545/1cc1e234-74fd-4aaa-9f9a-770fd1e87335)

**Comment by Xingrun-Xing** [comment]
My transformers==4.35.0 and tokenizers==0.14.1. May I ask about your environment?

**Comment by ChenMnZ** [comment]
@Xingrun-Xing 
You can try to half the learning rate of `let`.
